apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
    track: canary
  name: helloworld-canary
spec:
  ports:
    - nodePort: 36001
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld
    track: canary
  type: NodePort
