apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
    - nodePort: 36000
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: helloworld
  type: NodePort
