apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: helloworld
    track: stable
    version: v2
  name: helloworld-v2
spec:
  replicas: 5
  selector:
    app: helloworld
    track: stable
    version: v2
  template:
    metadata:
      labels:
        app: helloworld
        track: stable
        version: v2
    spec:
      containers:
        - image: jdeskins/hello-node:2.0
          name: helloworld
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /version
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
